### ISSUE TITLE
Obfuscation

### ISSUE THREAD

**Issue by mc-0bit** [RichardPaulAstley/PHC#20]
The below is super easy to reverse.
https://github.com/RichardPaulAstley/PHC/blob/cbe1dad90c86f20043cbf888cbba0bf998f1a69e/stats.js#L180 
 
Here are some steps in order to make the obfuscation better.
1. Obfuscate not the secretKey "generation" but the import/export functions as a whole.
2. Convert the contents of the export/import functions to [JSFuck](http://www.jsfuck.com)
3. Convert the JSFuck to a uft-8 byte array and save the result as a string in the export/import function. (you could do some more things here but this should be enough for you)
```js
  const encoder = new TextEncoder();
  console.log(encoder.encode(`some JSFuck code`).toString());
```
4. Convert this to JSFuck
```js
  const decoder = new TextDecoder("utf-8");
  const code = decoder.decode(new Uint8Array(myObfuscatedCodeString.split(","))); // needs to use the variable name from step 5 or the myObfuscatedCodeString variable needs to be in the global scope.
  eval(code);
```
5. Just put the JSFuck from step 4 into the export/import functions like this
```js
function importSave() {
  const myObfuscatedImportCodeString = `Very very long string of numbers` // make sure the variable name is not named this obviously
  [][(![]+[])[+[]]+(![]+[])[!+[]+!+[]]+(![]+[])[+!+[]].......
}
```

This is by no means perfect and will fall apart when the cheater knows JSFuck but at least it is something.

**Comment by RichardPaulAstley** [comment]
Thanks a lot for your help on that one. <3
I'm gonna work on it when I'll be done with my actual update for the game. It should be doable, even for me ;_; !
